language: erlang

env:
  global:
    - KERL_BUILD_BACKEND=git
    - VERSION=20.1.7
matrix:
  include:
    - sudo: required
      # The `erlang` tag has been temporarily removed from the Opal image,
      # until the first erlang builds for Xenial are available, so for now
      # we have to reference the image by its codename instead:
      language: __opal__
      dist: xenial
      group: edge
      env:
      - DIST=xenial
    - sudo: required
      dist: trusty
      group: edge
      env:
      - DIST=trusty
    - sudo: required
      env:
      - DIST=precise

before_install:
  - export OS_NAME=$(lsb_release -is | tr "A-Z" "a-z" || echo "osx")
  - export RELEASE=$(lsb_release -rs 2>/dev/null || sw_vers -productVersion | sed 's/^\([0-9][0-9]*.[0-9][0-9]*\).*/\1/')
  - export TARGET_DIR=${TRAVIS_BUILD_DIR}/${OS_NAME}/${RELEASE}/$(uname -m)
  - mkdir -p ${TARGET_DIR}

install:
  # Downloading to a location that's earlier in PATH than any pre-installed version.
  - curl -o "${HOME}/bin/kerl" https://raw.githubusercontent.com/yrashk/kerl/master/kerl
  - chmod +x "${HOME}/bin/kerl"

script: ./bin/compile

after_success: ./bin/archive

addons:
  artifacts:
    paths:
    - '${OS_NAME}'
    target_paths:
    - '/binaries/${OS_NAME}/${LSB_RELEASE}/${ARCH}'
