language: erlang

env:
  - ERLANG_VERSION=18.1
  - OS_NAME=$(lsb_release -is | tr "A-Z" "a-z" || echo "osx")
  - RELEASE=$(lsb_release -rs 2>/dev/null || sw_vers -productVersion | sed 's/^\([0-9][0-9]*.[0-9][0-9]*\).*/\1/')
  - TARGET_DIR=$HOME/archive/binaries/$OS_NAME/${RELEASE}/$(uname -m)

before_install:
  - kerl update releases
  - mkdir -p $TARGET_DIR

install:
  - true

script:
  - kerl build $ERLANG_VERSION $ERLANG_VERSION
  - kerl install $ERLANG_VERSION $HOME/otp/$ERLANG_VERSION
  - source $HOME/otp/$ERLANG_VERSION/activate


after_success:
  - pushd $HOME/otp
  - tar cjvf ${TARGET_DIR}/erlang-${ERLANG_VERSION}.tar.bz2 $ERLANG_VERSION

deploy:
  provider: s3
  local_dir: $HOME/archive
  skip_cleanup: true
  bucket: travis-otp-releases
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
