language: erlang

env:
  - ERLANG_VERSION=R13B04

before_install:
  - kerl update releases
  - mkdir $HOME/archive

install:
  - true

script:
  - kerl build $ERLANG_VERSION $ERLANG_VERSION
  - kerl install $ERLANG_VERSION $HOME/otp/$ERLANG_VERSION
  - source $HOME/otp/$ERLANG_VERSION/activate


after_success:
  - pushd $HOME/otp
  - tar cjvf $HOME/archive/erlang-${ERLANG_VERSION}-x86_64.tar.bz2 $ERLANG_VERSION

deploy:
  provider: s3
  upload_dir: ubuntu/12.04
  local_dir: $HOME/archive
  skip_cleanup: true
  bucket: travis-otp-releases
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
